package kopiDariRumah;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raiha
 */
interface pembayaran{
    public abstract int tax();
    public abstract int totalBayar();
    public abstract int totalBayar(int diskon);
    public abstract void setTime();
    public abstract void reset();
    public abstract void welcome();
}

public class Home extends javax.swing.JFrame implements pembayaran {

    /**
     * Creates new form Home
     */
    public int bayar=0;
    
    public Home() {
        initComponents();
        init();
    }
    
    public void init(){
        setTime();
        welcome();
        tax();
        totalBayar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtjumlah7 = new javax.swing.JTextField();
        txtjumlah2 = new javax.swing.JTextField();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        txtjumlah5 = new javax.swing.JTextField();
        txtjumlah6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        txtjumlah8 = new javax.swing.JTextField();
        txtjumlah9 = new javax.swing.JTextField();
        txtjumlah10 = new javax.swing.JTextField();
        txtjumlah11 = new javax.swing.JTextField();
        txtjumlah12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxayam = new javax.swing.JCheckBox();
        cbxnasigoreng = new javax.swing.JCheckBox();
        cbxrice = new javax.swing.JCheckBox();
        cbxmentai = new javax.swing.JCheckBox();
        cbxspaghetti = new javax.swing.JCheckBox();
        cbxplatter = new javax.swing.JCheckBox();
        cbxv60 = new javax.swing.JCheckBox();
        cbxkopi = new javax.swing.JCheckBox();
        cbxlong = new javax.swing.JCheckBox();
        cbxespresso = new javax.swing.JCheckBox();
        cbxgreen = new javax.swing.JCheckBox();
        cbxcappucino = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));

        jPanel2.setBackground(new java.awt.Color(224, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 24)); // NOI18N
        jLabel1.setText("KOPI DARI RUMAH");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setText("ORDER");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Coffee Beans_2.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Selamat Datang, ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nama");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Person.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("Menu Minuman:");

        jLabel11.setText("Harga:");

        jLabel12.setText("Jumlah:");

        jLabel13.setText("Menu Makanan:");

        jLabel14.setText("Harga:");

        jLabel15.setText("Jumlah:");

        jLabel16.setText("Rp. 26.000");

        jLabel17.setText("Rp. 32.000");

        jLabel18.setText("Rp. 23.000");

        jLabel19.setText("Rp. 35.000");

        jLabel20.setText("Rp. 18.000");

        jLabel21.setText("Rp. 28.000");

        txtjumlah7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah7ActionPerformed(evt);
            }
        });

        txtjumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah2ActionPerformed(evt);
            }
        });

        txtjumlah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah3ActionPerformed(evt);
            }
        });

        txtjumlah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah4ActionPerformed(evt);
            }
        });

        txtjumlah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah5ActionPerformed(evt);
            }
        });

        txtjumlah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah6ActionPerformed(evt);
            }
        });

        jLabel22.setText("Rp. 18.000");

        jLabel23.setText("Rp. 15.000");

        jLabel24.setText("Rp. 18.000");

        jLabel25.setText("Rp. 10.000");

        jLabel26.setText("Rp. 13.000");

        jLabel27.setText("Rp. 15.000");

        txtjumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah1ActionPerformed(evt);
            }
        });

        txtjumlah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah8ActionPerformed(evt);
            }
        });

        txtjumlah9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah9ActionPerformed(evt);
            }
        });

        txtjumlah10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah10ActionPerformed(evt);
            }
        });

        txtjumlah11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah11ActionPerformed(evt);
            }
        });

        txtjumlah12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah12ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Pesan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbxayam.setBackground(new java.awt.Color(224, 255, 255));
        cbxayam.setText("Ayam Geprek");
        cbxayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxayamActionPerformed(evt);
            }
        });

        cbxnasigoreng.setBackground(new java.awt.Color(224, 255, 255));
        cbxnasigoreng.setText("Nasi Goreng");

        cbxrice.setBackground(new java.awt.Color(224, 255, 255));
        cbxrice.setText("Rice Bowl Sapi");

        cbxmentai.setBackground(new java.awt.Color(224, 255, 255));
        cbxmentai.setText("Nasi Ayam Mentai");

        cbxspaghetti.setBackground(new java.awt.Color(224, 255, 255));
        cbxspaghetti.setText("Spaghetti Carbonara");

        cbxplatter.setBackground(new java.awt.Color(224, 255, 255));
        cbxplatter.setText("Kopi Dari Rumah Platter");

        cbxv60.setBackground(new java.awt.Color(224, 255, 255));
        cbxv60.setText("V60");
        cbxv60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxv60ActionPerformed(evt);
            }
        });

        cbxkopi.setBackground(new java.awt.Color(224, 255, 255));
        cbxkopi.setText("Kopi Susu");
        cbxkopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopiActionPerformed(evt);
            }
        });

        cbxlong.setBackground(new java.awt.Color(224, 255, 255));
        cbxlong.setText("Long Black");
        cbxlong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxlongActionPerformed(evt);
            }
        });

        cbxespresso.setBackground(new java.awt.Color(224, 255, 255));
        cbxespresso.setText("Espresso");
        cbxespresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxespressoActionPerformed(evt);
            }
        });

        cbxgreen.setBackground(new java.awt.Color(224, 255, 255));
        cbxgreen.setText("Green Tea Latte");
        cbxgreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgreenActionPerformed(evt);
            }
        });

        cbxcappucino.setBackground(new java.awt.Color(224, 255, 255));
        cbxcappucino.setText("Cappucino");
        cbxcappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcappucinoActionPerformed(evt);
            }
        });

        jButton3.setText("Bayar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Restaurant Menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                                    .addComponent(jLabel9))
                                .addGap(119, 119, 119)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbxv60)
                                                    .addComponent(jLabel10)
                                                    .addComponent(cbxkopi)
                                                    .addComponent(cbxlong)
                                                    .addComponent(cbxespresso)
                                                    .addComponent(cbxgreen)
                                                    .addComponent(cbxcappucino))
                                                .addGap(36, 36, 36)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel24)
                                                    .addComponent(jLabel23))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtjumlah12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtjumlah11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtjumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15))
                                                .addGap(33, 33, 33)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxayam)
                                            .addComponent(cbxnasigoreng)
                                            .addComponent(cbxrice)
                                            .addComponent(cbxmentai)
                                            .addComponent(cbxspaghetti))
                                        .addGap(18, 18, 18))
                                    .addComponent(cbxplatter, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton3)
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel30))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(104, 104, 104)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(148, 148, 148))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel16)))
                                            .addGap(235, 235, 235))))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel30)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxnasigoreng))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxkopi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(txtjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxayam)
                            .addComponent(cbxv60))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxrice)
                                    .addComponent(jLabel18)
                                    .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxmentai)
                                    .addComponent(cbxespresso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel20)
                                                .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxcappucino))
                                            .addComponent(cbxplatter))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cbxspaghetti)
                                                .addComponent(jLabel21)
                                                .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbxgreen)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(txtjumlah12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel26)
                                        .addComponent(txtjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxlong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(txtjumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(txtjumlah11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 132, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtjumlah7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah7ActionPerformed

    private void txtjumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah2ActionPerformed

    private void txtjumlah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah3ActionPerformed

    private void txtjumlah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah4ActionPerformed

    private void txtjumlah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah5ActionPerformed

    private void txtjumlah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah6ActionPerformed

    private void txtjumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah1ActionPerformed

    private void txtjumlah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah8ActionPerformed

    private void txtjumlah9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah9ActionPerformed

    private void txtjumlah10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah10ActionPerformed

    private void txtjumlah11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah11ActionPerformed

    private void txtjumlah12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tampil;
        int jumlah;
        tampil = "";
        if(cbxnasigoreng.isSelected()){
            jumlah = Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*26000;
            bayar=bayar+total;
            tampil += cbxnasigoreng.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxayam.isSelected()){
            jumlah = Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*32000;
            bayar=bayar+total;
            tampil += cbxayam.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxrice.isSelected()){
            jumlah = Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*23000;
            bayar=bayar+total;
            tampil += cbxrice.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxmentai.isSelected()){
            jumlah = Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*35000;
            bayar=bayar+total;
            tampil += cbxmentai.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxplatter.isSelected()){
            jumlah = Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil += cbxplatter.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxspaghetti.isSelected()){
            jumlah = Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*28000;
            bayar=bayar+total;
            tampil += cbxspaghetti.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxkopi.isSelected()){
            jumlah = Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil += cbxkopi.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxv60.isSelected()){
            jumlah = Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil += cbxv60.getText()+" x "+jumlah+"\t\tRp. "+total+"\n";
        }
        if(cbxlong.isSelected()){
            jumlah = Integer.parseInt(txtjumlah9.getText());
            int total;
            total=jumlah*13000;
            bayar=bayar+total;
            tampil += cbxlong.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxespresso.isSelected()){
            jumlah = Integer.parseInt(txtjumlah10.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil += cbxespresso.getText()+" x "+jumlah+"\t                             Rp. "+total+"\n";
        }
        if(cbxcappucino.isSelected()){
            jumlah = Integer.parseInt(txtjumlah11.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil += cbxcappucino.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(cbxgreen.isSelected()){
            jumlah = Integer.parseInt(txtjumlah12.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil += cbxgreen.getText()+" x "+jumlah+"\tRp. "+total+"\n";
        }
        if(totalBayar()==0){
            JOptionPane.showMessageDialog(null, "Anda Belum Menambahkan Item !!!","Warning",2);
        }
        else{
            String[] lines = tampil.split("\n");
            StringBuilder Tampil = new StringBuilder();
            for (int x = 0; x < lines.length; x++){
                Tampil.append((x+1) + ". " + lines[x] + "\n");
            }
            int diskon=0;
            if(bayar > 300000){
                diskon=20000;
                int totalBayar=totalBayar(diskon);
                jTextArea1.setText("""
                ****************Kopi Dari Rumah****************
                Time: """+jLabel28.getText()+"\n"+"Date: "+jLabel29.getText()+"\n"
                +"Nama Kasir : Rexi\n"
                +"***************************************************\n"
                +"Item:\t\t"+"Harga:\t\t"
                +"\n"+Tampil.toString()+"===================================="+"\n"
                +"\tSubTotal:\tRp. "+bayar+"\n"
                +"\tTax (10%):\tRp. "+tax()+"\n"
                +"\tDiskon:\tRp. "+diskon+"\n"
                +"\tTotal:\tRp. "+totalBayar(diskon));
            }else{
                jTextArea1.setText("""
                ****************Kopi Dari Rumah****************
                Time: """+jLabel28.getText()+"\n"+"Date: "+jLabel29.getText()+"\n"
                +"Nama Kasir : Rexi\n"
                +"***************************************************\n"
                +"Item:\t\t"+"Harga:\t\t"
                +"\n"+Tampil.toString()+"===================================="+"\n"
                +"\tSubTotal:\tRp. "+bayar+"\n"
                +"\tTax (10%):\tRp. "+tax()+"\n"
                +"\tTotal:\tRp. "+totalBayar());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxayamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxayamActionPerformed

    private void cbxv60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxv60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxv60ActionPerformed

    private void cbxkopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxkopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxkopiActionPerformed

    private void cbxlongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxlongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxlongActionPerformed

    private void cbxespressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxespressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxespressoActionPerformed

    private void cbxgreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgreenActionPerformed

    private void cbxcappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxcappucinoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(totalBayar()==0 && jTextArea1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Anda Belum Pesan, Silahkan Pesan Terlebih Dahulu !!!","Warning",2);
        }
        else{
            ImageIcon icon = new ImageIcon("src/Image/Cash.png");
            JOptionPane.showMessageDialog(null, "Pembayaran diterima, Pesanan akan segera diantar !!!","TERIMAKASIH",JOptionPane.INFORMATION_MESSAGE, icon);
            reset();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    @Override
    public void setTime(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                while(true){
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    String dateString = df.format(date);
                    jLabel28.setText(time.split(" ")[0]+" "+time.split(" ")[1]);
                    jLabel29.setText(dateString);
                }
            }
        }).start();
    }
    
    @Override
    public void welcome(){
        if(Register.name != null){
            jLabel7.setText(Register.name + "!");
        }else{
            jLabel7.setText("admin !");
        }
    }
    
    @Override
    public int tax(){
        return (int) (0.1*bayar); 
    }
    
    @Override
    public int totalBayar(){
        return tax()+bayar;
    }
    
    @Override
    public int totalBayar(int diskon){
        return tax()+(bayar-diskon);
    }
    
    @Override
    public void reset(){
        cbxnasigoreng.setSelected(false);
            cbxayam.setSelected(false);
            cbxrice.setSelected(false);
            cbxmentai.setSelected(false);
            cbxplatter.setSelected(false);
            cbxspaghetti.setSelected(false);
            cbxkopi.setSelected(false);
            cbxv60.setSelected(false);
            cbxlong.setSelected(false);
            cbxespresso.setSelected(false);
            cbxcappucino.setSelected(false);
            cbxgreen.setSelected(false);
            txtjumlah1.setText("");
            txtjumlah2.setText("");
            txtjumlah3.setText("");
            txtjumlah4.setText("");
            txtjumlah5.setText("");
            txtjumlah6.setText("");
            txtjumlah7.setText("");
            txtjumlah8.setText("");
            txtjumlah9.setText("");
            txtjumlah10.setText("");
            txtjumlah11.setText("");
            txtjumlah12.setText("");
            jTextArea1.setText("");
            bayar=0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxayam;
    private javax.swing.JCheckBox cbxcappucino;
    private javax.swing.JCheckBox cbxespresso;
    private javax.swing.JCheckBox cbxgreen;
    private javax.swing.JCheckBox cbxkopi;
    private javax.swing.JCheckBox cbxlong;
    private javax.swing.JCheckBox cbxmentai;
    private javax.swing.JCheckBox cbxnasigoreng;
    private javax.swing.JCheckBox cbxplatter;
    private javax.swing.JCheckBox cbxrice;
    private javax.swing.JCheckBox cbxspaghetti;
    private javax.swing.JCheckBox cbxv60;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah10;
    private javax.swing.JTextField txtjumlah11;
    private javax.swing.JTextField txtjumlah12;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtjumlah9;
    // End of variables declaration//GEN-END:variables
}